print ("Hello World")
print ("This is a test")
print ("A test of Script")
print ("Hopefully this will work")
print ("With Script mode")
print ("You can make multiple lines of code")
print ("All at the same time")
